DSEG SEGMENT
TABLE DB 0, 1, 4, 9, 16, 25, 36, 49, 64, 81
ASCIITABLE DB 30H, 31H, 32H, 33H, 34H, 35H, 36H, 37H, 38H, 39H
RETURN DB 13, 10, '$'
DSEG ENDS

SSEG SEGMENT STACK
SKTOP DB 20 DUP(0)
SSEG ENDS

CSEG SEGMENT
    ASSUME CS:CSEG, DS:DSEG, SS:SSEG
START: 
    MOV AX, DSEG ;初始化
    MOV DS, AX
    MOV AX, SSEG
    MOV SS, AX
    
    MOV AH, 01H  ;读入
    INT 21H
    AND AX, 000FH
    MOV CX, AX
	
    MOV AH, 09H   ;显示回车 \r\n
    MOV DX, OFFSET RETURN
    INT 21H

    MOV BX, OFFSET TABLE ;将偏移量保存到BX
    ADD BX, CX
    MOV AL, [BX]
    AND AX, 00FFH
    MOV BL, 10
    DIV BL
    AND AX, 00FFH
    MOV BX, OFFSET ASCIITABLE
    ADD BX, AX
    MOV DL, [BX]
    MOV AH, 02H
    INT 21H

    MOV BX, OFFSET TABLE ;将偏移量保存到BX
    ADD BX, CX
    MOV AL, [BX]
    AND AX, 00FFH
    MOV BL, 10
    DIV BL
    MOV AL, AH
    AND AX, 00FFH
    MOV BX, OFFSET ASCIITABLE
    ADD BX, AX
    MOV DL, [BX]
    MOV AH, 02H
    INT 21H

    MOV AH, 4CH
    MOV AL, 0
    INT 21H
CSEG ENDS
END START
